apiVersion: v1
kind: Secret
metadata:
  name: csi-s3-minio-secret
  namespace: kube-system
stringData:
  accessKeyID: <YOUR_ACCESS_KEY_ID>
  secretAccessKey: <YOUR_SECRET_ACCESS_KEY>
  endpoint: https://storage.yandexcloud.net